### PR TITLE
Update to 1.0.8 and switch to get the package from pypi

### PR DESCRIPTION
**Pull request by melund**

### CODE REVIEW

**Comment by melund** [comment]
Circle fails with `Error: HTTPError: 502 Server Error: Bad Gateway for url: https://conda.anaconda.org/conda-forge/linux-64/wcwidth-0.1.7-py34_0.tar.bz2: https://conda.anaconda.org/conda-forge/linux-64/wcwidth-0.1.7-py34_0.tar.bz2
` 

Maybe just need a restart

**Comment by jakirkham** [comment]
Please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.3.3`. This is needed to fix a build issue on AppVeyor.

**Comment by melund** [comment]
Ping. @scopatz can you merge this?

**Comment by melund** [comment]
Thanks.

**Pull request merged**
