### PR TITLE
update to 1.0.9

### PR DESCRIPTION
**Pull request by melund**

### CODE REVIEW

**Comment by melund** [comment]
@conda-forge-admin I have a weird issue with this failing? Can you help?

**Comment by melund** [comment]
@conda-forge-admin . Regenerating the feedstock fixed it. Can you or @scopatz merge it?

**Comment by melund** [comment]
No. Hold that a bit. I think something weird happened in the regenerate part.

**Comment by melund** [comment]
So now I think it is good to go.

**Comment by scopatz** [comment]
Thanks!

**Comment by jakirkham** [comment]
FYI `@conda-forge-admin` is a bot. `@conda-forge/core` is the core team. `@conda-forge/prompt_toolkit` is the maintainer team for this feedstock.

**Pull request merged**
